spring.application.name=ShopVerseAPIServices
server.servlet.context-path=/ShopVerseAPI
server.port=9090

spring.data.mongodb.uri=mongodb+srv://shopverse:HQB67Rkl1ZOtGFqn@cluster0.kbg6ivx.mongodb.net/shopverseDb?retryWrites=true&w=majority&appName=Cluster0	

logging.level.org.springframework.security=DEBUG